apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: pensjon-q2
  name: nidhogg
  namespace: pensjon-q2
spec:
  ingresses:
    - https://nidhogg.intern.dev.nav.no
  image: {{image}}
  port: 8080
  ttl: 3h
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: sporingslogg
  kafka:
    pool: nav-dev