name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: "Europe/Oslo"

      - name: Build and push image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: 'pensjon-q2'
      - name: Deploy to Nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: "dev-gcp"
          RESOURCE: ".nais/q2.yaml,.nais/kafka-q2.yaml"
          VAR: image=${{ steps.docker-build-push.outputs.image }} #
          TELEMETRY: ${{ steps.docker-build-push.outputs.telemetry }}